### ISSUE TITLE
KEEP IN MIND TO PROTECT YOUR ADC PORT

### ISSUE THREAD

**Issue by TonyVie** [gustavollps/esp32TTGO_i2s_scope#1]
Hi ! 
Do you have any advice about ADC port protection ?

Thanks !

**Comment by gustavollps** [comment]
Some Schottky diodes and an operational amplifier, or a voltage divider whit the diodes if the signal source allows a little bit of current draw. Unfortunately, I am away from home and out of equipment (not even resistors) due to the quarantine and have not tested any external protection circuit.
Use the link below to get an idea.
https://www.analog.com/en/technical-articles/protecting-adc-inputs.html

I am working on a simple demo video right now, check it out at the read.me file later.
