### ISSUE TITLE
Missing the backlight

### ISSUE THREAD

**Issue by marciolm** [gustavollps/esp32TTGO_i2s_scope#2]
Great Job, thank you for sharing!

Worked for me after a little modification to turn on the TFT backlight:

``#define TFT_BL          4  // Display backlight control pin``

and in the setup() section, before the  setup_screen(); :

``if(TFT_BL > 0) {``
``          pinMode(TFT_BL, OUTPUT);``
``          digitalWrite(TFT_BL, HIGH);``
 `` }``

I don't know if this is necessary for all TFT_eSPI library versions, my library was installed a while.

Márcio

**Comment by gustavollps** [comment]
Hi Marcio! Thanks for stating that. I was using a pretty old version myself too, 1.4.20, and the most recent is 2.2.6. 

After updating and reconfiguring it on the User_setup_select.h file, still got the code working all right. Not sure what your problem was, but you may update this library at the Arduino IDE on the library manager and check if it really was the library version.
