### ISSUE TITLE
Better button react?

### ISSUE THREAD

**Issue by middelbh** [gustavollps/esp32TTGO_i2s_scope#4]
Hi! I really like your sketch, worked out of the box. Just the problem with the buttons, they do not repond reliably. Did you have a chance to do more work on this? I would really appreciate!
Hans

**Comment by gustavollps** [comment]
Hi, middlebh! Glad that it worked for you! 

The buttons really are very slow and inconsistent in their functionality.
I am using the button2 library, and it is a very simple approach. As the calculation loop for the whole buffer runs about 3 times per second, if I'm not wrong, the library does not work well (it needs a faster loop).
I'm gonna try using the digital interrupts with auxiliary variables to fix that, but I am really busy with work for now, sorry!

You can try tweaking with the `#define LONGCLICK_MS 500`, try using about 1500. This #define improves the difference between a short and long click. Most of the clicks are recognized as long clicks due to the delay in the button2 loop.

If you manage to improve it, please let me know. I will be really glad!

**Comment by gustavollps** [comment]
I just tested some configurations. Defining the long click before including the button2.h library is not doing anything. 
The tests that I did were changing the values directly in the butten2.h file and it worked really really really better. It is probably the parameters that I was using in the video. I lost the library parameters that I had used after I formatted my computer.

I changed debounce to 20 and longclick to 500 in the button2.h:
```
#ifndef DEBOUNCE_MS
  #define DEBOUNCE_MS 20
#endif
#ifndef LONGCLICK_MS
  #define LONGCLICK_MS 500
#endif
```

Not sure why the library does not get the correct #define, but this way it worked. I think it is probably an Arduino IDE thing with the organization of the .ino files.

Thanks for opening this issue, I'm already updating the README to warn people of this.

**Comment by middelbh** [comment]
Hi Gustavo,

I made the changes, makes a big difference! Thanks, I will now start some testing!

Grtz Hans

Op 10 feb. 2021 om 04:53 heeft Gustavo Leite Lopes <notifications@github.com> het volgende geschreven:

﻿

I just tested some configurations. Defining the long click before including the button2.h library is not doing anything.
The tests that I did were changing the values directly in the butten2.h file and it worked really really really better. It is probably the parameters that I was using in the video. I lost the library parameters that I had used after I formatted my computer.

I changed debounce to 20 and longclick to 500 in the button2.h:

#ifndef DEBOUNCE_MS
  #define DEBOUNCE_MS 20
#endif
#ifndef LONGCLICK_MS
  #define LONGCLICK_MS 500
#endif


Not sure why the library does not get the correct #define, but this way it worked. I think it is probably an Arduino IDE thing with the organization of the .ino files.

Thanks for opening this issue, I'm already updating the README to warn people of this.
